[package]
name = "byte_sequencer"
version = "0.1.0"
authors = ["grey <fairingrey@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bytes = "0.4.12"

[dev-dependencies]
assert_matches = "1.1"
